# File my_project/update_router__add_network.py

import os
from pprint import pprint
os.environ.setdefault('CLOUDCIX_SETTINGS_MODULE', 'my_settings')

from cloudcix.api.compute import Compute

# Get a util function to get a session using the credentials in your settings file
from cloudcix.auth import get_admin_token

# ================================================================= #
#                      Get CloudCIX Token                           #
# ================================================================= #
token = get_admin_token()

# Configuration
router_id = 122                           # Change this to the router ID
new_network_name = 'new-test-network'     # Name for the new network
new_network_ipv4 = '10.0.42.0/24'        # IPv4 CIDR for the new network

# Update data - add new network to existing ones
update_data = {
    'networks': [
        {
            'ipv4': new_network_ipv4,
            'name': new_network_name
            # IPv6 and VLAN will be auto-generated
        }
    ]
}

print(f"Adding network '{new_network_name}' ({new_network_ipv4}) to router {router_id}...")
print("This will add a new network while preserving all existing networks.")
print("IPv6 and VLAN will be automatically generated by CloudCIX.")
print("\n" + "="*50 + "\n")

# ================================================================= #
#                      Add Network to Router                        #
# ================================================================= #
response = Compute.network_routers.partial_update(token=token, pk=router_id, data=update_data)

if response.status_code == 200:
    router_data = response.json()
    print("Network added successfully!")
    print("\nUpdated Router Details:")
    print("-" * 40)
    
    if 'content' in router_data:
        router = router_data['content']
        print(f"Router ID: {router.get('id', 'N/A')}")
        print(f"Name: {router.get('name', 'N/A')}")
        print(f"Updated: {router.get('updated', 'N/A')}")
        
        # Show all networks
        networks = router.get('networks', [])
        if networks:
            print(f"\nAll Networks ({len(networks)}):")
            print("-" * 30)
            for i, network in enumerate(networks, 1):
                print(f"Network {i}:")
                print(f"  Name: {network.get('name', 'N/A')}")
                print(f"  IPv4: {network.get('ipv4', 'N/A')}")
                print(f"  IPv6: {network.get('ipv6', 'N/A')}")
                print(f"  VLAN: {network.get('vlan', 'N/A')}")
                print()
        
elif response.status_code == 400:
    print("Bad Request - Invalid network configuration")
    print("Response:")
    pprint(response.json())
elif response.status_code == 404:
    print(f"Router with ID {router_id} not found.")
elif response.status_code == 403:
    print(f"Permission denied for router {router_id}.")
else:
    print(f"Error adding network: {response.status_code}")
    print("Response:")
    try:
        pprint(response.json())
    except:
        print(response.text)